default: compile

compile:
	./compile.sh

clean:
	./clean.sh

tab:
	g++ -O3 -Wall -lgsl -lgslcblas -fopenmp gridTabulatedPore.C -o gridTabulatedPore
	g++ -O3 -Wall -lgsl -lgslcblas -fopenmp gridTabulatedPore1.C -o gridTabulatedPore1
