#!/usr/bin/env perl
die "Usage: $0 templateFile varName values\n" unless @ARGV == 3;

my $templateFile = @ARGV[0];
my $varName = @ARGV[1];
my $n = @ARGV[2];

# Read the template.
open(DAT, $templateFile) || die("Could not open file $index!\n");
@data=<DAT>;
#my @indexList = split(' ', $data[0]);
close(DAT);

# Write the config files.
for ($i = 0; $i < $n; $i++) {
    my $val = $i;
    my $outFile = $templateFile . "$val.namd";
    open(OUT, ">" . "$outFile") || die("Could not open file $outFile!\n");

    my $defLine = "set $varName $val\n";
    print OUT $defLine;
    foreach (@data) {
	print OUT $_;
    }
}
