#!/usr/bin/env perl
die "Usage: $0 inputFileName\n" unless @ARGV == 1;

my ($source) = @ARGV[0];
my $dest = $source . ".pmf";

print "Extracting forces from file `$source'...\n";

die "$source does not exist!\n" unless -e $source;
die "$dest exists!\n" if -e $dest;

my $awkCmd = "'{print \$5,\$8}'";
system "grep \"SMD  \" $source | awk $awkCmd > $dest";
print "Results written to $dest\n"
