#!/usr/bin/env perl
die "Usage: $0 inputFileName\n" unless @ARGV == 1;

my ($source) = @ARGV;
my $dest = $source . ".force";

print "Extracting forces from file `$source'...\n";

die "$source does not exist!\n" unless -e $source;
die "$dest exists!\n" if -e $dest;

my $awkCmd = "'{print \$6,\$7,\$8,\$10,\$11,\$12}'";
system "grep \"PAIR INTERACTION: \" $source | awk $awkCmd > $dest";
print "Results written to $dest\n"
