#!/usr/bin/env perl
my $mss = "mss.ncsa.uiuc.edu";

die "Usage: $0 fileName\n" unless @ARGV == 1;

my ($source) = @ARGV;

die "$source does not exist!\n" unless -e $source;

my $size = (stat $source)[7];	# Get size so we can tell MSS

print "Uploading $source...\n";
print "Size: $size\n";

#my $ftpcmds = << "EOFTP;"
#sunique
#quote allo $size
#put $source
#EOFTP;

my $ftpcmds = "jcomer\nput $source\nbye\n";

system "echo \"$ftpcmds\" | ftp $mss &";
